### ISSUE TITLE
Preview error

### ISSUE THREAD

**Issue by ikunya** [flathub/org.gnome.gitlab.somas.Apostrophe#6]
Apostrophe shows error during to show preview.

```
Exception in thread preview-converter:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/python3.8/site-packages/apostrophe/preview_converter.py", line 50, in __do_convert
    text = helpers.pandoc_convert(text, to="html5", args=args)
  File "/app/lib/python3.8/site-packages/apostrophe/helpers.py", line 169, in pandoc_convert
    return pypandoc.convert_text(
  File "/app/lib/python3.8/site-packages/pypandoc/__init__.py", line 102, in convert_text
    return _convert_input(source, format, 'string', to, extra_args=extra_args,
  File "/app/lib/python3.8/site-packages/pypandoc/__init__.py", line 324, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "1" during conversion: b'pandoc: getCurrentDirectory:getWorkingDirectory: does not exist (Current working directory no longer exists)\n'
```

where is working directory?

**Comment by somas95** [comment]
I need a better reproducer, step by step if possible. The project's own bugtracker would be a better place to discuss this anyway

Obtén l'Outlook per a l'Android<https://aka.ms/AAb9ysg>

________________________________
From: Ikuya AWASHIRO ***@***.***>
Sent: Monday, May 17, 2021 3:43:17 PM
To: flathub/org.gnome.gitlab.somas.Apostrophe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [flathub/org.gnome.gitlab.somas.Apostrophe] Preview error (#6)


Apostrophe shows error during to show preview.

Exception in thread preview-converter:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/python3.8/site-packages/apostrophe/preview_converter.py", line 50, in __do_convert
    text = helpers.pandoc_convert(text, to="html5", args=args)
  File "/app/lib/python3.8/site-packages/apostrophe/helpers.py", line 169, in pandoc_convert
    return pypandoc.convert_text(
  File "/app/lib/python3.8/site-packages/pypandoc/__init__.py", line 102, in convert_text
    return _convert_input(source, format, 'string', to, extra_args=extra_args,
  File "/app/lib/python3.8/site-packages/pypandoc/__init__.py", line 324, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "1" during conversion: b'pandoc: getCurrentDirectory:getWorkingDirectory: does not exist (Current working directory no longer exists)\n'


where is working directory?

**Comment by rusty-snake** [comment]
For me this happens if I open file through the document portal.

STR:
- `flatpak run --file-forwarding --nofilesystem=host:reset org.gnome.gitlab.somas.Apostrophe @@ path/to/file.md @@`
- Preview

**Comment by somas95** [comment]
I mean. You're overriding the permissions I need for some things to work. Without a neighbour files API I need filesystem read access, there's no way around it
